# Generated by Django 4.1 on 2022-08-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('category', models.IntegerField(choices=[(0, 'Fashion'), (1, 'Mobiles'), (2, 'Home'), (3, 'Appliances'), (4, 'Grocery'), (5, 'Personal Care'), (6, 'Sports'), (7, 'Electronics'), (8, 'Toys & Baby')], default=0, verbose_name='Products Category')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Product Cost')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount Price')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
