# Generated by Django 4.1 on 2022-08-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_products_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('mobiles', 'Mobiles'), ('home', 'Home'), ('appliances', 'Appliances'), ('grocery', 'Grocery'), ('personal_care', 'Personal Care'), ('sports', 'Sports'), ('electronics', 'Electronics'), ('toys_baby', 'Toys & Baby')], default=0, max_length=255, verbose_name='Products Category'),
        ),
    ]
