# Generated by Django 4.1 on 2022-08-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
