# Generated by Django 4.1 on 2022-08-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_products_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='updated',
        ),
    ]
