# Generated by Django 4.1 on 2022-08-19 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_products_created_alter_products_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-created']},
        ),
    ]
